from pathlib import Path
import os

SRC_PATH = Path(os.path.dirname(os.path.abspath(__file__)))
PROJECT_PATH = SRC_PATH.parents[0]
DATABASE_PATH = Path("./database")
TEMPLATES_PATH = PROJECT_PATH / "templates"
KEYS_PATH = DATABASE_PATH / "KEYS"

CHAMPIONS_IMAGES_PATH = DATABASE_PATH / "CHAMPION_IMAGES"
THUMBNAIL_IMAGES_PATH = DATABASE_PATH / "THUMBNAILS"

JSON_PATH = DATABASE_PATH / "GAMES_DATA"
STREAMS_PATH = DATABASE_PATH / "STREAMS"
STREAMERS_SUMMONERS_NAMES_JSON_PATH = DATABASE_PATH / "streamers_summoner_names.json"

EDITED_VIDEOS_INFO_PATH = DATABASE_PATH / "edited_videos_info.xlsx"

TAB_TEMPLATE = TEMPLATES_PATH / "tab_template.PNG"
STREAMER_SUMMONER_NAME_INDICATOR_TEMPLATE = TEMPLATES_PATH / "streamer_summoner_name_indicator.PNG"
FRIZ_QUADRATA_BOLD_FONT_PATH = TEMPLATES_PATH / "Friz Quadrata Bold BT.ttf"

INTRO_VIDEO_PATH = TEMPLATES_PATH / "intro.mp4"
OUTRO_VIDEO_PATH = TEMPLATES_PATH / "outro.mp4"

TOKEN_PICKLE_PATH = KEYS_PATH / "token.pickle"
CLIENT_SECRETS_PATH = KEYS_PATH / "client_secrets.json"
RIOT_API_KEY_PATH = KEYS_PATH / "RIOT_API_KEY.json"

STREAMERS_PATH = DATABASE_PATH / "STREAMERS.json"